### ISSUE TITLE
On starting, set configuration to be the set of channels enabled on the scope

### ISSUE THREAD

**Issue by mubes** [glscopeclient/scopehal-apps#353]
User feedback is that enabling all channels on the scope on startup is not appreciated, so we should start with the set of channels the user already has set up.

For the degenerate case of no channels enabled, I would suggest that we fall back to the old behaviour of enabling all (analog) ones.

**Comment by azonenberg** [comment]
Should be done now. We enable all analog channels on USB instruments and only the active channels on standalone ones. If none enabled, we enable the first channel.

Any deviations from this behavior are likely due to driver bugs not correctly reporting enabled channels, and should be filed as new bugs against the offending driver.
