### ISSUE TITLE
Clicking "Start (normal trigger)" causes erratic scope behavior

### ISSUE THREAD

**Issue by dan-gies** [glscopeclient/scopehal-apps#476]
## System Info:
Glscopeclient version: 0.1-0ec5f20
OS: Windows 10
Oscilloscope: Siglent SDS6204A

## Description:
When I click "Start (normal trigger)" in glscopeclient, the oscilloscope alternates between run/stop. I expect the scope run continuously with "normal" trigger, as it does when I do it locally. See attached video for undesirable behavior.

https://user-images.githubusercontent.com/108100309/185998562-0760c97d-346f-4738-86d0-db8c14609e9f.mp4

**Comment by azonenberg** [comment]
This is normal and intended behavior and is due to the fact that SCPI APIs on most scopes lack any kind of synchronization primitives.

If you leave the scope in "normal" trigger and try to download a waveform for channel 1, then 2, then 3, then 4 you might get waveforms from four different trigger events. The only way to avoid this within the current APIs is to stop the trigger, grab all of the data, then re-arm it.

A better solution (which we are pushing for in all of our conversations with vendors) would be a producer/consumer flow where  the scope queues up the acquired data from all four channels, sends it out via socket/USB, then immediately re-arms the trigger. No vendor currently implements this, however, so we're stuck working with the APIs they give us.
